# POST http://localhost:50305 HTTP/1.1
POST https://api.evm.eosnetwork.com HTTP/1.1
content-type: application/json

{"method":"eth_getCode","params":[ "0xbbbbbbbbbbbbbbbbbbbbbbbb4aa6ec0192000000", "0x5ba3aa" ],"id":1,"jsonrpc":"2.0"}
