# POST http://localhost:50305 HTTP/1.1
POST https://api.evm.eosnetwork.com HTTP/1.1
content-type: application/json

{"method":"eth_estimateGas","params":[
    {
      "from": "0xaa2f34e41b397ad905e2f48059338522d05ca534",
      "to": "0xbbbbbbbbbbbbbbbbbbbbbbbb4aa6ec0192000000",
      "value": "0xde0b6b3a7640000",
      "gasPrice": "0x22ecb25c00",
      "data": "0x"
    }
],"id":1,"jsonrpc":"2.0"}