name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        platform: [linux-x64, macos-arm64, macos-x64, win-x64]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun test
      - run: bun build --compile ./bin/cli.ts --outfile eos-evm-miner-${{ matrix.platform }}
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            eos-evm-miner-*
